### ISSUE TITLE
setpred4DEE代码是不是写错了

### ISSUE THREAD

**Issue by zwq2018** [HangYang-NLP/DE-PPN#18]
line115-124行左右      
  if self.role_layers:
            for i, layer_module in enumerate(self.role_layers):
                if self.return_intermediate:
                    all_hidden_states = all_hidden_states + (event_role_embed,)
                layer_outputs = layer_module(
                    # event_role_embed, doc_sent_context
                    event_role_embed, batch_span_context
                    # event_role_embed, doc_span_sent_context
                )

这里是不是输入decoder的event_role_embed没更新，相当于只有一层

**Comment by HangYang-NLP** [comment]
非常感谢提出问题，这里的 line 124 应该是  event_role_embed = layer_outputs[0]，后续添加 event_role_hidden_states = event_role_embed。很抱歉上传的代码出现这个问题（上传的代码是为了方便阅读，规范重写后的代码）。我会做出相应修改。
