### ISSUE TITLE
怎么运行？

### ISSUE THREAD

**Issue by simon-p-j-r** [HangYang-NLP/DE-PPN#19]
博主你好，我是一个超级萌新，读了您的论文之后想进行复现，但是不知道代码应该怎么运行，虽然你可能觉得这个问题很蠢，但是我真的研究了小半天，运行bash run_multi.sh会报错，直接运行run_main.py也会报“object of type 'NoneType' has no len()”

**Comment by GJZhang2866** [comment]
可以检查一下dee_task.py 的DEETaskSetting中的文件名称，或者检查一些数据是否放在对应的位置上。

**Comment by BWKevin** [comment]
> 可以检查一下dee_task.py 的DEETaskSetting中的文件名称，或者检查一些数据是否放在对应的位置上。
请问运行bash run_single.sh会出现如下错误，在self.tokenizer = BERTChineseCharacterTokenizer.from_pretrained(self.setting.bert_model)这一步会出错并且最终错误如下：
requests.exceptions.SSLError: TLS/SSL connection has been closed (EOF) (_ssl.c:1131)

**Comment by GJZhang2866** [comment]
这个错误是由于网络问题无法下载bert模型导致的，建议手动下载并放置于项目目录文件夹中 https://huggingface.co/bert-base-chinese
