### ISSUE TITLE
ModuleNotFoundError: No module named 'DEE.dee_helper'

### ISSUE THREAD

**Issue by KyrieIrving24** [HangYang-NLP/DE-PPN#2]

**Comment by Spico197** [comment]
It seems the repo is not complete and a lot of files are missing. Maybe this is a patch to the original Doc2EDAG codes?

**Comment by KyrieIrving24** [comment]
> It seems the repo is not complete and a lot of files are missing. Maybe this is a patch to the original Doc2EDAG codes?

yeah，but the author may should release the complete code
